### ISSUE TITLE
Any way to keep Myo unlocked?

### ISSUE THREAD

**Issue by pzula** [stolksdorf/myo.js#11]
I'm using this library to control a sumobot, and having to unlock for every gesture is slowing down how responsive the robot is. Do you have any suggestions for keeping the Myo unlocked the whole time that it is running?

**Comment by alanhortz** [comment]
Hello Brian, 

It works well ! thanks !

**Comment by jaypozo** [comment]
I haven't been able to get this to work - there was an SDK update released Jan 15, 2015. Perhaps that has broken this feature?

**Comment by jaypozo** [comment]
My bad - the npm module is not synced with this repo. This does work.

**Comment by stolksdorf** [comment]
I keep forgetting that that npm doesn't auto-update, sorry guys! Updated the npm module with 1.3
