### ISSUE TITLE
Error on accessing raw EMG data

### ISSUE THREAD

**Issue by timotius02** [stolksdorf/myo.js#17]
When trying to access the raw EMG data, this error pop up:

<code>Uncaught InvalidStateError: Failed to execute 'send' on 'WebSocket': Still in CONNECTING state.</code>

**Comment by stolksdorf** [comment]
You may be calling that `myo.streamEMG()` function before the socket connection is made. Try waiting for the `connected` event, like this:

```
myo.on('connected', function(){
	myo.streamEMG(true);
});
```

**Comment by timotius02** [comment]
It works, thanks!

**Comment by stolksdorf** [comment]
I'll update the docs to be more clear :)
