### ISSUE TITLE
'oriontation' data.y actually x?

### ISSUE THREAD

**Issue by matifol** [stolksdorf/myo.js#21]
I have tried to figure out if my calibration might be wrong, but it seems like 'oriontation' data.y is actually x coordinates?

**Comment by stolksdorf** [comment]
The orientation data being fed from the Myo is a [quaternion](http://en.wikipedia.org/wiki/Quaternion), each component of this data doesn't relate directly to a real-world coordinate but is used as a rotation. Instead, you'll have to use the quaternion to get the rotation you're looking for. 

One method is to get Euler angles (yaw, pitch, roll). If you just want to check your calibration the [Diagnostics Page](http://diagnostics.myo.com/) should help out, the spinning cube helps. Also you should contact Thalmic support if you think the IMU calibration is off.

**Comment by matifol** [comment]
Thanks a lot for the help! I'll take a closer look at it later tonight.

This issue can be closed.
