### ISSUE TITLE
MYO Changed gesture "thumb to pinky" to double tap-"thumb to middle finger"

### ISSUE THREAD

**Issue by yves-s** [stolksdorf/myo.js#22]
I just used my MYO after some time, updated it and there is now double tap-"thumb to middle finger" instead of "thumb to pinky" to unlock the device.

**Comment by stolksdorf** [comment]
I don't see how this is an issue. Thalmic has found that the thumb to pinky gesture was difficult for most people, so they developed a new better gesture. I have intentionally kept Myo.js 'pose agnostic', so if they change what poses they emit the library won't break.
