### ISSUE TITLE
Failed on HTTPS sites.

### ISSUE THREAD

**Issue by PhillippOhlandt** [stolksdorf/myo.js#23]
Hey I want to build myo control on my websites wich use https.

The websocket cannot be initiated.

Uncaught SecurityError: Failed to construct 'WebSocket': An insecure WebSocket connection may not be initiated from a page loaded over HTTPS.

**Comment by stolksdorf** [comment]
Hmm, there doesn't seem to be any easy solution. It might require a change to the way Myo Connect does it's web socket. I'll look into it.

**Comment by PhillippOhlandt** [comment]
Yes it would be cool if the PC and Mac programm can be updated to support wss://

**Comment by stolksdorf** [comment]
This issue was moved to thalmiclabs/myo.js#1
